[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force Netlify to not use cached node_modules for Prisma
[[plugins]]
  package = "@netlify/plugin-cache"
  [plugins.inputs]
    paths = ["node_modules/.cache"] 